{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.0/printer-1.0.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosArm64Main-1.0.0.klib",
          "url": "printer-iosarm64-1.0.0.klib",
          "size": 101998,
          "sha512": "28df00624e2bb40f9102c30800b1cc6e6264cf18b33d2ca9b05129fe5658b7c2efdc5b4af81363a9cccee430aa068c74c56d0fafba541d0ab639cfb8d1ce9487",
          "sha256": "4d631e34fbc0622ccdea62ec38a66d72f626f84a4a57118112d3b8de9a4c7f89",
          "sha1": "cc3dd011c07832a05d312f754ae12bbb20e33ad4",
          "md5": "921adc0b4d6b6fae6f97a2bf95964340"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iosarm64-1.0.0-sources.jar",
          "url": "printer-iosarm64-1.0.0-sources.jar",
          "size": 19961,
          "sha512": "336b7edd133869485a45d62ae1b55b72723d7f879d9eaf681d974ed64d770e88d8a19dfcd1ebbbfade65aa3a95927a00d2ee43827a3602523ea7c06857cc8586",
          "sha256": "277a21d3d3af0c760314bb84bf629200a1e15a1a413d0d9d3ea9fba85d159331",
          "sha1": "57adf220f516de0364bc244b52b18fa109d21710",
          "md5": "ef3473254d044718a24e1c5dc0929593"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosarm64-1.0.0-metadata.jar",
          "url": "printer-iosarm64-1.0.0-metadata.jar",
          "size": 3925,
          "sha512": "e62d8b9ef473e2290c362009f88eab2dbf701ab2d79cfc9717483a97cd27373b52b267aa7d27454ea38aaf7188f7bb91e6d4c2001d5b7b0079449f8e19db7114",
          "sha256": "e6fbfc85dca69e399ecb42aa75eb7cf3813781f16ec2779976b855f012f316f4",
          "sha1": "aee9a1cb7133ec7ac54ee68d57903d49b803a1cc",
          "md5": "27ab9378037016504280f1fd52492636"
        }
      ]
    }
  ]
}
