{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.0/printer-1.0.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosArm64Main-1.0.0.klib",
          "url": "printer-iosarm64-1.0.0.klib",
          "size": 101998,
          "sha512": "28df00624e2bb40f9102c30800b1cc6e6264cf18b33d2ca9b05129fe5658b7c2efdc5b4af81363a9cccee430aa068c74c56d0fafba541d0ab639cfb8d1ce9487",
          "sha256": "4d631e34fbc0622ccdea62ec38a66d72f626f84a4a57118112d3b8de9a4c7f89",
          "sha1": "cc3dd011c07832a05d312f754ae12bbb20e33ad4",
          "md5": "921adc0b4d6b6fae6f97a2bf95964340"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iosarm64-1.0.0-sources.jar",
          "url": "printer-iosarm64-1.0.0-sources.jar",
          "size": 19961,
          "sha512": "336b7edd133869485a45d62ae1b55b72723d7f879d9eaf681d974ed64d770e88d8a19dfcd1ebbbfade65aa3a95927a00d2ee43827a3602523ea7c06857cc8586",
          "sha256": "277a21d3d3af0c760314bb84bf629200a1e15a1a413d0d9d3ea9fba85d159331",
          "sha1": "57adf220f516de0364bc244b52b18fa109d21710",
          "md5": "ef3473254d044718a24e1c5dc0929593"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosarm64-1.0.0-metadata.jar",
          "url": "printer-iosarm64-1.0.0-metadata.jar",
          "size": 3925,
          "sha512": "d536de8d5bd58b7f1cf240b559996fa53fe2b2fd1fd1b9ed834e427e00d2cd9d9b1c20bbafc70ad877d7614dbcdc066381bd778665ed442bdbfa7e17e6db1c69",
          "sha256": "ea9948434dce38c127d3e3baabd1c05f09f5af46837cbb9e1c7c1cf78185fb3d",
          "sha1": "b6aebae7fbcecd4788e8ea08d0578a353a7dfad2",
          "md5": "5078408ce2c5922dca865f2e7ea82fcd"
        }
      ]
    }
  ]
}
