{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.1/printer-1.0.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosArm64Main-1.0.1.klib",
          "url": "printer-iosarm64-1.0.1.klib",
          "size": 102000,
          "sha512": "145c646fc41d6c366b0f8159a34e0e49f4c70bd3e5cd466fac70ff482566d4b14d42523a3861ec889b2f73fbfda4b0d0bb58d0145bce29304b57a062f815dd93",
          "sha256": "45e1d369a02c507f45fc6fb04992a1a26dba5308e01253172546944e5b089693",
          "sha1": "17f0b5def989b681b8ab87e31b8251cdd7965f45",
          "md5": "9be123838c7cfc2e6332c24b957fcbce"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iosarm64-1.0.1-sources.jar",
          "url": "printer-iosarm64-1.0.1-sources.jar",
          "size": 19960,
          "sha512": "8388f49d4f7c90ea587f71b5930ac662369fb59ac974b2821097f2b9f3b337fa46f10a9bf678136955bf89f3fafe1f38b17c75d56d8ddb56ce2b2253b1ff7dd7",
          "sha256": "b5fb2d4b0b5e63bc8c9e3c807114233ec84983abc3eebaa60048b090054593d0",
          "sha1": "38cab8b51defe1a34a20c11d310fc8265d99b3fa",
          "md5": "30ecd157b23c66c6adb3f47e84e860fc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosarm64-1.0.1-metadata.jar",
          "url": "printer-iosarm64-1.0.1-metadata.jar",
          "size": 3925,
          "sha512": "6bf478f600a42eb934bde20f8f1d410bcaa454a1dbcc7b49081a58432a01a40f88f5a624f337e5fb6ae7054d82f3213e81952430323db5af87859323012e9f2f",
          "sha256": "e7b3e9965e2b1684befb37f7d4fce454584261e27029bf741796194a54ef67b3",
          "sha1": "60c1334445df62aff575502df924602a657c1698",
          "md5": "abd4ef84f28e0f8cedd9f50eb7dfa887"
        }
      ]
    }
  ]
}
