{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.2/printer-1.0.2.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.2.aar",
          "size": 138178,
          "sha512": "f8097b2deeb18d04def49490cebb0ff4c1c669a386807a80a74fe14c49249e3228774ba32474ce458fa83ef239148a29972627e59422113d6b2cacde2e0059ce",
          "sha256": "eae84afc481b5cb107d305e41f95d74418ae7cbb10fad7342088bcfdbfea643d",
          "sha1": "518da4d712dbffdb98cf2c8ed6ab8a6f1f88ad15",
          "md5": "b1034ec471f7f836f1b5af29243aea1d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.2.aar",
          "size": 138178,
          "sha512": "f8097b2deeb18d04def49490cebb0ff4c1c669a386807a80a74fe14c49249e3228774ba32474ce458fa83ef239148a29972627e59422113d6b2cacde2e0059ce",
          "sha256": "eae84afc481b5cb107d305e41f95d74418ae7cbb10fad7342088bcfdbfea643d",
          "sha1": "518da4d712dbffdb98cf2c8ed6ab8a6f1f88ad15",
          "md5": "b1034ec471f7f836f1b5af29243aea1d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "printer-android-1.0.2-sources.jar",
          "url": "printer-android-1.0.2-sources.jar",
          "size": 26306,
          "sha512": "0de3dc6e088214527cf4a3791d48d7797411c67484f0e73d1110356f9cfcdb43388601a14fda1b703399da53556882ccc7fe9440366832d2fe1a5815027325e3",
          "sha256": "ed8b4714f88cf6aae149337b18805f2fc4854a557924b6e53a1f5632f4b2f7e3",
          "sha1": "34f1b8d419e75dc6cee63763c108d4e220933e1a",
          "md5": "70b4a8f2a9ae69a35998b442acbe4a27"
        }
      ]
    }
  ]
}
