{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.1/printer-1.0.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-1.0.1.jar",
          "url": "printer-jvm-1.0.1.jar",
          "size": 86450,
          "sha512": "02ce5804957abfc435518ccd5047e3c611bb5546ce00f2805781a0317f3ec519b9876d4c8e07014486dfbdc27b029868627d2e9e11b5d321ae71f8cbd6e4fba0",
          "sha256": "3aaf4dcf2e6108d2d41ee1e5e6764258569357de510179e9f8f8e0309ab68f99",
          "sha1": "a9d3d9fa074be8258cb25a11ff9d75ccd77b40f5",
          "md5": "2480418dc3dab1ffb05856564ec89aa7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-1.0.1.jar",
          "url": "printer-jvm-1.0.1.jar",
          "size": 86450,
          "sha512": "02ce5804957abfc435518ccd5047e3c611bb5546ce00f2805781a0317f3ec519b9876d4c8e07014486dfbdc27b029868627d2e9e11b5d321ae71f8cbd6e4fba0",
          "sha256": "3aaf4dcf2e6108d2d41ee1e5e6764258569357de510179e9f8f8e0309ab68f99",
          "sha1": "a9d3d9fa074be8258cb25a11ff9d75ccd77b40f5",
          "md5": "2480418dc3dab1ffb05856564ec89aa7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "printer-jvm-1.0.1-sources.jar",
          "url": "printer-jvm-1.0.1-sources.jar",
          "size": 18534,
          "sha512": "e8c5cac00bdb8b4cc536fb61fd6df0ff9352b77944c94b0295f144a29efbd9a5fe5f54555102c2ffa17a4f78b2ec01a036f9a421ec0a9cf59fa8122c734866bc",
          "sha256": "205a7c2efb6eecb63f910cf92d282eb050b91beee5f83a8b9b978bb34bbaff55",
          "sha1": "ad2063601f48b06318604a8982d8f50e8c56b05f",
          "md5": "7b23dc7fffcf4ce58fb23496c87031c2"
        }
      ]
    }
  ]
}
