{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.1/printer-1.0.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.1.aar",
          "size": 137518,
          "sha512": "73006cd25ddeeed8c8097ae7029e470374d1ddf77fd6e9fe2c01511b6f2b6b079794282250584f7bd006db538c70df13ced10804a8890158e785fadaa31e67ab",
          "sha256": "a260bcd66cb055ab3289135320bc2ad91c41a4cbc3c3466576ae27bf0841bf5a",
          "sha1": "016d861ac3c507228c29cc10119bee7e139f0fe1",
          "md5": "2d71cb1c24b0675ad17e04a67b0ca448"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.1.aar",
          "size": 137518,
          "sha512": "73006cd25ddeeed8c8097ae7029e470374d1ddf77fd6e9fe2c01511b6f2b6b079794282250584f7bd006db538c70df13ced10804a8890158e785fadaa31e67ab",
          "sha256": "a260bcd66cb055ab3289135320bc2ad91c41a4cbc3c3466576ae27bf0841bf5a",
          "sha1": "016d861ac3c507228c29cc10119bee7e139f0fe1",
          "md5": "2d71cb1c24b0675ad17e04a67b0ca448"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "printer-android-1.0.1-sources.jar",
          "url": "printer-android-1.0.1-sources.jar",
          "size": 26306,
          "sha512": "0de3dc6e088214527cf4a3791d48d7797411c67484f0e73d1110356f9cfcdb43388601a14fda1b703399da53556882ccc7fe9440366832d2fe1a5815027325e3",
          "sha256": "ed8b4714f88cf6aae149337b18805f2fc4854a557924b6e53a1f5632f4b2f7e3",
          "sha1": "34f1b8d419e75dc6cee63763c108d4e220933e1a",
          "md5": "70b4a8f2a9ae69a35998b442acbe4a27"
        }
      ]
    }
  ]
}
