{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.0/printer-1.0.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.0.aar",
          "size": 137473,
          "sha512": "3b22adce476dea74a711c5a14f87c9e2ab9d55fd4dcea6954ec48887ac665e7cf55333ab42d4c64ecc9a7c6890ccf0bfc80d509b05ed64651472a3b3c6413624",
          "sha256": "714a23be6f68d25f8c0b33ee1026dadf36faf99301d3da784cc255b3f92dad09",
          "sha1": "d3a5b8601001596506bf8057f1a03757fa3f9a3b",
          "md5": "ff595b329329a37ee99a3d91628a0459"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.0.aar",
          "size": 137473,
          "sha512": "3b22adce476dea74a711c5a14f87c9e2ab9d55fd4dcea6954ec48887ac665e7cf55333ab42d4c64ecc9a7c6890ccf0bfc80d509b05ed64651472a3b3c6413624",
          "sha256": "714a23be6f68d25f8c0b33ee1026dadf36faf99301d3da784cc255b3f92dad09",
          "sha1": "d3a5b8601001596506bf8057f1a03757fa3f9a3b",
          "md5": "ff595b329329a37ee99a3d91628a0459"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "printer-android-1.0.0-sources.jar",
          "url": "printer-android-1.0.0-sources.jar",
          "size": 26307,
          "sha512": "0580251a193a7f46617def4f8550bdfaafe9bacb6345178a7731814887e00036c91c1429a6e266b8843e8a1ed07aac0386f8ae0eefa7149feef87a32de56f0d3",
          "sha256": "e3e7bbf462e4f23985c19e05862bd5185d8e5e2c14f1210979203c22fa777fe8",
          "sha1": "e26017823a7eda890b930e395d4b651d41dd5e06",
          "md5": "f0d1bda7da337a45133a80055b634c1b"
        }
      ]
    }
  ]
}
