{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/2.1.1/printer-2.1.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-2.1.1.klib",
          "url": "printer-iossimulatorarm64-2.1.1.klib",
          "size": 220564,
          "sha512": "a402fab7ff12612807df0081b27da5d4dc3910b8b714a386a9bdcaa052c1a38cbeb8633782682aa3a7a8b9a887745716fd21a2c3d78b7ed6e530ce12d4eb3b57",
          "sha256": "4e7c7acd8ca55ea723a231cf8d0978bbdecdd57fc8aa9a86bb4e3ac44ab9244f",
          "sha1": "e73f99d2b225e1fe9019c85d826d068d64161862",
          "md5": "c6e00f120995a91833b27be230758daa"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.1.1-sources.jar",
          "url": "printer-iossimulatorarm64-2.1.1-sources.jar",
          "size": 47217,
          "sha512": "c8816f6cc3a96611d1597ddda7359940a58ac03c5c141a6cf68f56370c18605dd42a07a1b014ed3cfeb734f83178eaf213dd3784a2012b302e3432ce13bede8b",
          "sha256": "17a70e12d8e9fc7f58945f0bd6c60dc203932752f7fa9ca67f451346612d85a3",
          "sha1": "181261300590a41df897c005bd1aa5161afd19a6",
          "md5": "924cdc08c61bea67faf1dae640dd3209"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iossimulatorarm64-2.1.1-metadata.jar",
          "url": "printer-iossimulatorarm64-2.1.1-metadata.jar",
          "size": 6200,
          "sha512": "801eee09a55371fd29321cd5ca80b94fddb898602a65a356b9f55c83efb2acff049dece22d72d7da70ad0d189f33b19f65c4f2f751c6fa8b62cbd6c332427dd5",
          "sha256": "71d9de7ac0ce3c04313c0214aa33334aa9cfb3a1de075edccbd5d96e1c6da528",
          "sha1": "5035fb3e56ebd55dec1cead31521ba79398412c7",
          "md5": "18210529557dcf83b2d32d8a97c0e6f8"
        }
      ]
    }
  ]
}
