{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.0/printer-1.0.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-1.0.0.jar",
          "url": "printer-jvm-1.0.0.jar",
          "size": 86465,
          "sha512": "609b2b1b95f5001ecd9304d95538216e7ab20f480f8204aea87f903202b37c70114fc2f7e2493ba46b55a90ac6c5b2b67c662b653dec4d2e03e833cac74a8266",
          "sha256": "855560e9567f3c94784ee8553bd00cd20ce4508126821b8562da0439c18af777",
          "sha1": "10d51030a832b77b3ea3c1712b641ec9f9ac7ec0",
          "md5": "715842c201c6088332689f142e010c0e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "com.fazecast",
          "module": "jSerialComm",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-jvm-1.0.0.jar",
          "url": "printer-jvm-1.0.0.jar",
          "size": 86465,
          "sha512": "609b2b1b95f5001ecd9304d95538216e7ab20f480f8204aea87f903202b37c70114fc2f7e2493ba46b55a90ac6c5b2b67c662b653dec4d2e03e833cac74a8266",
          "sha256": "855560e9567f3c94784ee8553bd00cd20ce4508126821b8562da0439c18af777",
          "sha1": "10d51030a832b77b3ea3c1712b641ec9f9ac7ec0",
          "md5": "715842c201c6088332689f142e010c0e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "printer-jvm-1.0.0-sources.jar",
          "url": "printer-jvm-1.0.0-sources.jar",
          "size": 18535,
          "sha512": "e7067284bb182c6cce6406dbae94570fff391a7c98250cb9d123d5a86e9cae54687014743fc3e0cf2fb3f0219b0c8ae365cb431564707b4bfd6d773d857b6c18",
          "sha256": "aa4b147d6f961f889757ba5752dc832495b0e2639d7dcb2b2a09d143711cfb1f",
          "sha1": "16d04e22795417676a3531be198179be9b576208",
          "md5": "b6238b51430b626f97eb5982e7e05e85"
        }
      ]
    }
  ]
}
