{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.1/printer-1.0.1.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.1.aar",
          "size": 137420,
          "sha512": "6048d6544e8d754d080a434b52d1f294202130ac06d2a8783aa3a18f55d44d313564283f24570db1496fa22253d4080da10303964c3e8c8141caaa49e8e3127e",
          "sha256": "e908a86a6c23179af96645f90b233050ed3f540ca92290003a62bbb771c78219",
          "sha1": "3b7a277a68b739b8df0e794910713ec86f8e4bbb",
          "md5": "966eb28ae00fb45734f764880a37ff16"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "printer-release.aar",
          "url": "printer-android-1.0.1.aar",
          "size": 137420,
          "sha512": "6048d6544e8d754d080a434b52d1f294202130ac06d2a8783aa3a18f55d44d313564283f24570db1496fa22253d4080da10303964c3e8c8141caaa49e8e3127e",
          "sha256": "e908a86a6c23179af96645f90b233050ed3f540ca92290003a62bbb771c78219",
          "sha1": "3b7a277a68b739b8df0e794910713ec86f8e4bbb",
          "md5": "966eb28ae00fb45734f764880a37ff16"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "printer-android-1.0.1-sources.jar",
          "url": "printer-android-1.0.1-sources.jar",
          "size": 26475,
          "sha512": "42da7fe1dd12581e4189b5667223597e5a643014c2ed8c9e5ce3cd7d15d4a1e965222a369430fde86bb39173979186808a2a6f69d1a2736a9825ff8678593316",
          "sha256": "fc4840a928749287786127aec37046e1cf5bd493bb98253eb98287fa8d2383a4",
          "sha1": "df8ab21cc1a3cd327ef5af39c68e41223219c611",
          "md5": "940ad4166ed1aea47c2f17a2d7b18882"
        }
      ]
    }
  ]
}
