{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.0/printer-1.0.0.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-1.0.0.klib",
          "url": "printer-iossimulatorarm64-1.0.0.klib",
          "size": 102063,
          "sha512": "a5645c23fffaf8e67e939642bbb330885de20dc01586d2b396bf8a36f5a41c5a598fa584478bb2c60eb8082115ba0f7ec5d388fa821e02a4619bb7e2fe7b86b3",
          "sha256": "3dea0a05099bbf205dd56b567e31be613bde4a541ccad1acf69b92853f17a9a4",
          "sha1": "9588d3a84524e5a5996f5e710be02764e6453689",
          "md5": "ae920682b750287a0e6dd9b3e0d69f69"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iossimulatorarm64-1.0.0-sources.jar",
          "url": "printer-iossimulatorarm64-1.0.0-sources.jar",
          "size": 19961,
          "sha512": "336b7edd133869485a45d62ae1b55b72723d7f879d9eaf681d974ed64d770e88d8a19dfcd1ebbbfade65aa3a95927a00d2ee43827a3602523ea7c06857cc8586",
          "sha256": "277a21d3d3af0c760314bb84bf629200a1e15a1a413d0d9d3ea9fba85d159331",
          "sha1": "57adf220f516de0364bc244b52b18fa109d21710",
          "md5": "ef3473254d044718a24e1c5dc0929593"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "printer-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3925,
          "sha512": "507cc182448d8a4cb253f35c36a27d1f16fcc5379124c5fc85d7fc9a16933970a95bec87f9968116443948110024247c15f82eda4456517b606a47d954dc0107",
          "sha256": "3525ac494c8e07440dbf323b6bb79896529db9e9df531bb32ce9f66f4c338b7f",
          "sha1": "c018c3e84fff66d0d8585f52f71bccec4388021c",
          "md5": "738aa5ae3158665a02ee34fc10a69cea"
        }
      ]
    }
  ]
}
