{
  "formatVersion": "1.1",
  "component": {
    "url": "../../printer/1.0.4/printer-1.0.4.module",
    "group": "io.github.ringga-dev",
    "module": "printer",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iosSimulatorArm64Main-1.0.4.klib",
          "url": "printer-iossimulatorarm64-1.0.4.klib",
          "size": 141903,
          "sha512": "d5fcf241ff7109b42bd4f4943ed65b93e64174550b9c531f7d54944c50532c6ae1e8d3929d480e2e6c5a5b5622589e6602b8e8d660584a4fd06dc34ae3478bd2",
          "sha256": "0ade499a5e1354c429997de42a41a2213ebdafc6cc6c9c37a0c67997e12cfa09",
          "sha1": "1754634bfce671a06caa821e34842d457e17b184",
          "md5": "b2670927022bdf78f9b63c6044211060"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "printer-iossimulatorarm64-1.0.4-sources.jar",
          "url": "printer-iossimulatorarm64-1.0.4-sources.jar",
          "size": 29051,
          "sha512": "3012a14e0956ded202582d7bd0fbff764900fd1ee086a79615b336837490268804e4600790b627cf4120ff6849dc354d9b9d481c5c140f0381e09a780e0392e7",
          "sha256": "17540db8edeaaa656c0b1f599e78d05b939e2cac456b101ac202450eacb43679",
          "sha1": "9fab37349c55703b0f5174729a9728f3cb4b2a67",
          "md5": "d3dc5dc685bdcf22653813627efa5ad4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "printer-iossimulatorarm64-1.0.4-metadata.jar",
          "url": "printer-iossimulatorarm64-1.0.4-metadata.jar",
          "size": 5647,
          "sha512": "35c57b24c3d43d696ff55367f1d36e094e75b98c6148a92c6a1af896f600d0a3b4f356fffb934b1cdb55648b3df432c6a06074f8fd1ade441d4f05da05d9d95c",
          "sha256": "0f77e13172ceba0b3e51684708fa70d0e4bf5d27e5d0d5c06a9d22fcf2c0b5bc",
          "sha1": "5a0b0deed606aa028f48b084394f63ffeaa37dfe",
          "md5": "32aaed0b230bdc83555d495f18dc0e52"
        }
      ]
    }
  ]
}
